services:
  backend:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
  db:
    image: mysql:8.0
    platform: Linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "demo"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    ports:
      - 33306:3306
  frontend:
    build:
      context: .
      dockerfile: app-front/Dockerfile
    volumes:
      - ./app-front:/app-front
      - /app-front/node_modules
    ports:
      - 3000:3000
volumes:
  mysql_data:
